import { useRouter } from "next/navigation";
import React, {useEffect} from "react";
import withAuth from "./withAuth";


function Home() {
  const router = useRouter();

  useEffect(() => {
    const token = window.localStorage.getItem("token");

    if (!token) {
      router.push("/login");
    }
  }, []);

  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href='/admin/user'>User</Link> */}
    </>
  );
}

export default withAuth(Home)
